USE sakila;

-- 1. List the number of films per category.

SELECT category_id,COUNT(film_id)
FROM film_category
GROUP BY category_id;

-- 2. Retrieve the store ID, city, and country for each store.
 
 SELECT store_id ,country , city
 FROM address a
 JOIN store s
 USING (address_id)
 JOIN city ci
 USING (city_id)
 JOIN country
 USING(country_id);
 
-- 3. Calculate the total revenue generated by each store in dollars.

SELECT staff_id,SUM(amount) total_revenue
FROM payment
GROUP by staff_id;

-- 4. Determine the average running time of films for each category.

SELECT category_id,ROUND(AVG(length),2) average_duration
FROM film_category fc
JOIN film f 
USING (film_id)    -- ON fc.film_id = f.film_id
GROUP BY category_id;

